# Save stop words

import os, pickle
from nltk.corpus import stopwords
from nltk import download
import ssl


try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context
download('stopwords')
stop_words = stopwords.words('english')
# stop_words.remove("more")
stop_words = set(stop_words)

stop_words.add("less")

stop_words.add("much")
stop_words.add("reason")
stop_words.add("reasons")
stop_words.add("case")
stop_words.add("cases")
stop_words.add("etc")
stop_words.add("question")
stop_words.add("questions")
stop_words.add("people")
stop_words.add("ok")
stop_words.add("everything")
stop_words.add("something")
stop_words.add("anything")
stop_words.add("many")
stop_words.add("way")
stop_words.add("jpg")
stop_words.add("vice-versa")
stop_words.add("fact")
stop_words.add("choice")
stop_words.add("library")
stop_words.add("canvas")
stop_words.add("java")
stop_words.add("video")
stop_words.add("logn")
stop_words.add("n")
stop_words.add("wpf")
stop_words.add("app")
stop_words.add("software")
stop_words.add("times")
stop_words.add("terms")
stop_words.add("overall")
stop_words.add("python")
stop_words.add("mouseenter")
stop_words.add("mouseout")
stop_words.add("jquery")
stop_words.add("imho")
stop_words.add("fm")
stop_words.add("scenario")
stop_words.add("crypto")
stop_words.add("algorithms")
stop_words.add("problem")
stop_words.add("pki")
stop_words.add("decrypt")
stop_words.add("encrypt")
stop_words.add("key")
stop_words.add("messages")
stop_words.add("cryptography")
stop_words.add("encryption")
stop_words.add("block")
stop_words.add("asymmetric")
stop_words.add("symmetric")
stop_words.add("decryption")
stop_words.add("purposes")
stop_words.add("language")
stop_words.add("classes")
stop_words.add("php")
stop_words.add("javascript")
stop_words.add("ruby")
stop_words.add("c")
stop_words.add("c++")
stop_words.add("others")
stop_words.add("code")
stop_words.add("perl")
stop_words.add("vm")
stop_words.add("true")
stop_words.add("interpreter")
stop_words.add("faq")
stop_words.add("im")
stop_words.add("cql3")
stop_words.add("orm")
stop_words.add("rails")
stop_words.add("db")
stop_words.add("tkey")
stop_words.add("tvalue")
stop_words.add("list")
stop_words.add("items")
stop_words.add("elements")
stop_words.add("log")
stop_words.add("option")
stop_words.add("btw")
stop_words.add("surprised")
stop_words.add("strange")
stop_words.add("jvm")
stop_words.add("advice")
stop_words.add("lot")
stop_words.add("lots")
stop_words.add("j9")
stop_words.add("c2")
stop_words.add("c1")
stop_words.add("guess")
stop_words.add("firefox")
stop_words.add("safari")
stop_words.add("google-chrome")
stop_words.add("opera")
stop_words.add("diff2")
stop_words.add("js")
stop_words.add("scenarios")
stop_words.add("vice")
stop_words.add("vesa")

with open(os.path.join(os.pardir, "data", "stop_words.pkl"), 'wb') as stop_words_file:
    pickle.dump(stop_words, stop_words_file)
